# Generated by Django 4.2 on 2023-04-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chara', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='pics')),
                ('about', models.TextField()),
            ],
        ),
    ]
